_: {
  imports = [
    ./config/bootloader.nix
    ./config/desktop
    ./config/networking/static.nix
    ./config/networking/wireless.nix
    ./config/packages
    ./config/nixvim
    ./config/ssh.nix
    ./config/system.nix
    ./config/users.nix
    ./hardening/bootloader.nix
    ./services/comin
    ./services/controller.nix
    ./services/dnsmasq.nix
    ./services/file-browser.nix
    ./services/gitea.nix
    ./services/gitea-runner.nix
    ./services/grafana.nix
    ./services/guacamole.nix
    ./services/jenkins.nix
    ./services/k3s.nix
    ./services/netbox.nix
    ./services/nextcloud.nix
    ./services/nginx/default.nix
    ./services/password-store.nix
    ./services/prometheus.nix
    ./services/restic.nix
    ./services/sshd.nix
    ./services/semaphore
    ./services/syncthing
    ./services/wireguard-server.nix
    ./services/wireguard-client.nix
    ./services/zabbix.nix
    ./virtualisation/guest.nix
    ./virtualisation/hypervisor.nix
    ./virtualisation/whonix.nix
  ];
}
